[package]
name = "faf-rust-replayserver"
version = "0.2.3"
authors = ["Igor Kotrasinski <i.kotrasinsk@gmail.com>"]
edition = "2018"

[features]
local_db_tests = []
process_tests = []
bench = []

[[bin]]
name = "faf_rust_replayserver"
path = "src/main.rs"

[[bin]]
name = "test_sigint"
path = "src/process_test/sigint.rs"
required-features = ["process_tests"]

[[bin]]
name = "test_process_panic"
path = "src/process_test/process_panic.rs"
required-features = ["process_tests"]

[dependencies]
async-compression = { version = "0.3.7", features = ["tokio", "zstd"] }
async-stream = "0.3.0"
config = { version = "0.11.0", features = ["yaml"] }
env_logger = "0.8.3"
faf-replay-parser = "0.5.1"
futures = "0.3.13"
lazy_static = "1.4.0"
log = "0.4.11"
prometheus_exporter = "0.8.0"
rand = "0.8.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
signal-hook = "0.3.7"
sqlx = { version = "0.5.1", features = ["runtime-tokio-rustls", "mysql", "time"] }
thiserror = "1.0.24"
time = { version = "0.2.26", features = ["std"] }
tokio-stream = { version = "0.1.5", features = ["net"] }
tokio-util = "0.6.5"
weak-table = "0.3.0"

[dependencies.tokio]
version = "1.4.0"
features = ["sync", "net", "io-util", "rt", "macros", "test-util", "time"]

[dev-dependencies]
faux = "0.0.7"
tempfile = "3.2.0"
