[package]
name = "faf-rust-replayserver"
version = "0.1.0"
authors = ["Igor Kotrasinski <i.kotrasinsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.8"
signal-hook = "0.3.0"
log = "0.4.11"
env_logger = "0.8.2"
thiserror = "1.0.22"
async-stream = "0.3.0"
tokio-util = "0.6.0"
tokio-stream = "0.1.2"
weak-table = "0.3.0"
serde = { version = "1.0.123", features = ["derive"] }
config = { version = "0.10.1", features = ["yaml"] }

[dependencies.tokio]
version = "1.0.1"
features = ["sync", "net", "io-util", "rt", "macros", "test-util", "time"]

[dev-dependencies]
faux = "0.0.7"
