# vim: et:ts=4:sts=4:sw=4
name: Release
on:
    release:
        types: [published]

jobs:
    docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Extract tag name
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

            - uses: docker/setup-buildx-action@v1

            - uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and publish docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: faforever/faf-rust-replayserver:${{ steps.vars.outputs.tag }}
